vim.api.nvim_set_hl(0, 'Normal', { fg = '#e9e9e9' })
vim.api.nvim_set_hl(0, 'NormalNC', { bg = '#000000' })
vim.api.nvim_set_hl(0, 'MoreMsg', { link = 'Normal' })
vim.api.nvim_set_hl(0, 'ModeMsg', { link = 'Normal' })
vim.api.nvim_set_hl(0, 'Question', { link = 'Normal' })
vim.api.nvim_set_hl(0, 'QuickFixLine', { link = 'Normal' })
vim.api.nvim_set_hl(0, 'Underlined', { underline = true })

vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#aaaaaa' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#aaaaaa', bg = '#000000' })
vim.api.nvim_set_hl(0, 'WinBar', { link = 'StatusLine' })
vim.api.nvim_set_hl(0, 'WinBarNC', { link = 'StatusLineNC' })

vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#222222' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#aaaaaa', bg = '#222222' })
vim.api.nvim_set_hl(0, 'ColorColumn', { link = 'CursorLine' })

vim.api.nvim_set_hl(0, 'Visual', { bg = '#252a47' })

vim.api.nvim_set_hl(0, 'MatchParen', { bold = true })

vim.api.nvim_set_hl(0, 'Keyword', { fg = '#ffffff', bold = true })
vim.api.nvim_set_hl(0, 'Conditional', { link = 'Keyword' })
vim.api.nvim_set_hl(0, 'Repeat', { link = 'Keyword' })

vim.api.nvim_set_hl(0, 'Type', { fg = '#a9a9a9' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#d4d4d4' })
vim.api.nvim_set_hl(0, 'Function', { link = 'Identifier' })
vim.api.nvim_set_hl(0, 'Statement', { link = 'Identifier' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#d4d4d4', bold = true })
vim.api.nvim_set_hl(0, '@variable', { link = 'Identifier' })
vim.api.nvim_set_hl(0, 'Constant', { italic = true, fg = '#bebebe' })
vim.api.nvim_set_hl(0, 'String', { link = 'Constant' })
vim.api.nvim_set_hl(0, 'Tag', { link = 'Constant' })
vim.api.nvim_set_hl(0, 'Label', { link = 'Constant' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#939393' })
vim.api.nvim_set_hl(0, 'Comment', { italic = true, fg = '#686868' })
vim.api.nvim_set_hl(0, 'Title', { fg = '#a9a9a9' })
vim.api.nvim_set_hl(0, 'Directory', { bold = true })

vim.api.nvim_set_hl(0, 'NonText', { fg = '#525252' })
vim.api.nvim_set_hl(0, 'LineNr', { link = 'NonText' })
vim.api.nvim_set_hl(0, 'SignColumn', { link = 'NonText' })
vim.api.nvim_set_hl(0, 'SpecialKey', { link = 'NonText' })
vim.api.nvim_set_hl(0, 'Folded', { link = 'NonText' })
vim.api.nvim_set_hl(0, 'Conceal', { link = 'NonText' })

vim.api.nvim_set_hl(0, 'Operator', { fg = '#7d7d7d' })
vim.api.nvim_set_hl(0, 'Delimiter', { link = 'Operator' })

vim.api.nvim_set_hl(0, 'Added', { fg = '#6bff88' })
vim.api.nvim_set_hl(0, 'Removed', { fg = '#ff6b81' })
vim.api.nvim_set_hl(0, 'Changed', { fg = '#ffdb6b' })
vim.api.nvim_set_hl(0, 'DiffAdd', { link = 'Added' })
vim.api.nvim_set_hl(0, 'DiffDelete', { link = 'Removed' })
vim.api.nvim_set_hl(0, 'DiffChange', { link = 'Changed' })
vim.api.nvim_set_hl(0, 'DiffText', { bg = '#201c0d' })

vim.api.nvim_set_hl(0, 'Error', { fg = '#ff6b81' })
vim.api.nvim_set_hl(0, 'DiagnosticError', { link = 'Error' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', { undercurl = true, sp = '#ff6b81' })
vim.api.nvim_set_hl(0, 'NvimInvalid', { undercurl = true, sp = '#ff6b81' })
vim.api.nvim_set_hl(0, 'ErrorMsg', { link = 'Error' })

vim.api.nvim_set_hl(0, 'Warn', { fg = '#ffdb6b' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { link = 'Warn' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', { undercurl = true, sp = '#ffdb6b' })
vim.api.nvim_set_hl(0, 'WarningMsg', { link = 'Warn' })

vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#8398ff' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo', { undercurl = true, sp = '#8398ff' })
vim.api.nvim_set_hl(0, 'Todo', { link = 'DiagnosticInfo' })

vim.api.nvim_set_hl(0, 'DiagnosticOk', { fg = '#8398ff' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineOk', { undercurl = true, sp = '#8398ff' })

vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#8398ff' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', { undercurl = true, sp = '#8398ff' })

vim.api.nvim_set_hl(0, 'DiagnosticUnnecessary', { underdotted = true })
vim.api.nvim_set_hl(0, 'DiagnosticDeprecated', { strikethrough = true })

vim.api.nvim_set_hl(0, 'Cursor', { fg = '#e9e9e9', bg = '#8398ff' })
vim.api.nvim_set_hl(0, 'TermCursor', { link = 'Cursor' })

vim.api.nvim_set_hl(0, 'Search', { fg = '#e9e9e9', bg = '#4e5b99' })
vim.api.nvim_set_hl(0, 'IncSearch', { link = 'Search' })
vim.api.nvim_set_hl(0, 'CurSearch', { link = 'Search' })

vim.api.nvim_set_hl(0, 'LspReferenceText', { bg = '#333333' })
vim.api.nvim_set_hl(0, 'LspReferenceRead', { link = 'LspReferenceText' })
vim.api.nvim_set_hl(0, 'LspReferenceWrite', { link = 'LspReferenceText' })

vim.api.nvim_set_hl(0, 'SpellBad', { link = 'DiagnosticUnderlineError' })
vim.api.nvim_set_hl(0, 'SpellCap', { link = 'DiagnosticUnderlineWarn' })
vim.api.nvim_set_hl(0, 'SpellRare', { link = 'DiagnosticUnderlineInfo' })
vim.api.nvim_set_hl(0, 'SpellLocal', { link = 'DiagnosticUnderlineWarn' })

vim.api.nvim_set_hl(0, 'FloatTitle', { link = 'FloatBorder' })
vim.api.nvim_set_hl(0, 'LspInfoBorder', { link = 'FloatBorder' })
vim.api.nvim_set_hl(0, 'NormalFloat', { link = 'Normal' })
vim.api.nvim_set_hl(0, 'Pmenu', { link = 'Normal' })
vim.api.nvim_set_hl(0, 'PmenuSel', { bg = '#333333' })

vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = '#6bff88' })
vim.api.nvim_set_hl(0, 'GitSignsStagedAdd', { fg = '#265c31' })
vim.api.nvim_set_hl(0, 'GitSignsStagedAddNr', { link = 'GitSignsStagedAdd' })
vim.api.nvim_set_hl(0, 'GitSignsDelete', { fg = '#ff6b81' })
vim.api.nvim_set_hl(0, 'GitSignsStagedDelete', { fg = '#5c262f' })
vim.api.nvim_set_hl(0, 'GitSignsStagedDeleteNr', { link = 'GitSignsStagedDelete' })
vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = '#ffdb6b' })
vim.api.nvim_set_hl(0, 'GitSignsStagedChange', { fg = '#5c4f26' })
vim.api.nvim_set_hl(0, 'GitSignsStagedChangeNr', { link = 'GitSignsStagedChange' })
vim.api.nvim_set_hl(0, 'GitSignsAddInline', { bg = '#15331b' })
vim.api.nvim_set_hl(0, 'GitSignsDeleteInline', { bg = '#33151a' })
vim.api.nvim_set_hl(0, 'GitSignsChangeInline', { bg = '#332c15' })

vim.api.nvim_set_hl(0, 'GitConflictCurrent', { bg = '#471e24' })
vim.api.nvim_set_hl(0, 'GitConflictIncoming', { bg = '#1e4726' })
vim.api.nvim_set_hl(0, 'GitConflictAncestor', { bg = '#473e1e' })
vim.api.nvim_set_hl(0, 'GitConflictCurrentLabel', { bg = '#5c262f', bold = true })
vim.api.nvim_set_hl(0, 'GitConflictIncomingLabel', { bg = '#265c31', bold = true })
vim.api.nvim_set_hl(0, 'GitConflictAncestorLabel', { bg = '#5c4f26', bold = true })

vim.api.nvim_set_hl(0, 'TreesitterContext', { bg = '#222222' })
vim.api.nvim_set_hl(0, 'TreesitterContextLineNumber', { fg = '#525252', bg = '#222222' })

vim.api.nvim_set_hl(0, 'TelescopeBorder', { link = 'FloatBorder' })
vim.api.nvim_set_hl(0, 'TelescopeNormal', { bg = '#111111' })
vim.api.nvim_set_hl(0, 'TelescopeSelection', { link = 'CursorLine' })
vim.api.nvim_set_hl(0, 'TelescopeMatching', { link = 'Search' })