name: Check if generated themes were committed

on: [push, pull_request]

jobs:
  check-generate:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate themes
        run: ./generate

      - name: Check for changes
        run: git diff --exit-code
